db:
  adapter: mysql
  name: qor_example
  user: root
  password: pqor_example
  host: 127.0.0.1
  port: 3306
  debug: true
secret: secret
limit: 5
redis:
  host: localhost
session:
  name: sessionid
  adapter: cookie
